# yml omega 6.txt (configuration Netlify CMS avec autorisations admin)
backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

# Configuration des autorisations - seul l'admin peut publier/modifier/supprimer
publish_mode: editorial_workflow

collections:
  - name: "content"
    label: "Contenu du site"
    files:
      - label: "Offres d'emploi"
        name: "jobs"
        file:  "public/data/content.json"
        # Seul l'admin peut modifier ce fichier
        permissions:
          create: admin
          update: admin
          delete: admin
        fields:
          - label: "Offres d'emploi"
            name: "content"
            widget: "list"
            # Workflow de publication nécessitant approbation admin
            publish: false
            fields:
              - { label: "ID", name: "id", widget: "string", required: false, hint: "Laisser vide pour génération automatique" }
              - { label: "Titre du poste", name: "title", widget: "string" }
              - { label: "Entreprise", name: "company", widget: "string" }
              - { label: "Lieu", name: "location", widget: "string" }
              - { label: "Type de contrat", name: "type", widget: "string", hint: "Ex: CDI, CDD, Stage, Consultant, Freelance, etc." }
              - { label: "Secteur d'activité", name: "sector", widget: "string", hint: "Ex: Humanitaire, Agriculture, Éducation, Santé, etc." }
              - { label: "Date de publication", name: "date", widget: "datetime" }
              - { label: "Date d'expiration", name: "expirationDate", widget: "datetime" }
              - { label: "Description du poste", name: "description", widget: "text" }
              - { label: "Exigences et compétences", name: "requirements", widget: "text" }
              - { label: "Expérience requise", name: "experience", widget: "string", hint: "Ex: 3 ans minimum, Débutant accepté, etc." }
              - { label: "Niveau d'éducation", name: "education", widget: "string", hint: "Ex: BAC, BTS, LICENCE, MASTER, DOCTORAT, etc." }
              - { label: "Compétences spécifiques", name: "skills", widget: "list", default: [], hint: "Ajouter une compétence puis cliquer + pour en ajouter une autre" }
              - { label: "Salaire", name: "salary", widget: "string", required: false, hint: "Ex: Selon expérience, 300.000 FCFA, Négociable, etc." }
              - { label: "Auteur", name: "author", widget: "string", default: "Admin" }
              - { label: "Lien de postulation", name: "applicationUrl", widget: "string", required: false, hint: "URL directe pour postuler (optionnel)" }
              - { label: "Tags supplémentaires", name: "tags", widget: "list", required: false, default: [], hint: "Tags pour améliorer la recherche" }
              - { label: "Statut de publication", name: "published", widget: "boolean", default: false, hint: "Cocher pour publier l'offre (admin seulement)" }
              - { label: "Approbation admin", name: "adminApproved", widget: "hidden", default: false }