# yml omega 6.txt (configuration Netlify CMS avec autorisations admin)
backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

# Configuration des autorisations - seul l'admin peut publier/modifier/supprimer
publish_mode: editorial_workflow

collections:
  - name: "content"
    label: "Contenu du site"
    files:
      - label: "Offres d'emploi"
        name: "jobs"
        file:  "public/data/content.json"
        # Seul l'admin peut modifier ce fichier
        permissions:
          create: admin
          update: admin
          delete: admin
        fields:
          - label: "Offres d'emploi"
            name: "content"
            widget: "list"
            # Workflow de publication nécessitant approbation admin
            publish: false
            fields:
              - { label: "ID", name: "id", widget: "string", required: false, hint: "Laisser vide pour génération automatique" }
              - { label: "Titre du poste", name: "title", widget: "string", required: false }
              - { label: "Entreprise", name: "company", widget: "string", required: true }
              - { label: "Lieu", name: "location", widget: "string", required: false }
              - { label: "Type de contrat", name: "type", widget: "string", required: false, hint: "Ex: CDI, CDD, Stage, Consultant, Freelance, etc." }
              - { label: "Secteur d'activité", name: "sector", widget: "string", required: false, hint: "Ex: Humanitaire, Agriculture, Éducation, Santé, etc." }
              - { label: "Date de publication", name: "date", widget: "datetime", required: false }
              - { label: "Date d'expiration", name: "expirationDate", widget: "datetime", required: false }
              - { label: "Description du poste", name: "description", widget: "text", required: false }
              - { label: "Exigences et compétences", name: "requirements", widget: "text", required: false }
              - { label: "Expérience requise", name: "experience", widget: "string", required: false, hint: "Ex: 3 ans minimum, Débutant accepté, etc." }
              - { label: "Niveau d'éducation", name: "education", widget: "string", required: false, hint: "Ex: BAC, BTS, LICENCE, MASTER, DOCTORAT, etc." }
              - { label: "Compétences spécifiques", name: "skills", widget: "list", default: [], required: false, hint: "Ajouter une compétence puis cliquer + pour en ajouter une autre" }
              - { label: "Salaire", name: "salary", widget: "string", required: false, hint: "Ex: Selon expérience, 300.000 FCFA, Négociable, etc." }
              # NOUVEAUX CHAMPS POUR LES COORDONNÉES SPÉCIFIQUES
              - { label: "Email de contact spécifique", name: "contactEmail", widget: "string", required: false, hint: "Email spécifique pour cette offre (laisser vide pour utiliser l'email général)" }
              - { label: "WhatsApp spécifique", name: "contactWhatsApp", widget: "string", required: false, hint: "Numéro WhatsApp spécifique pour cette offre (laisser vide pour utiliser le WhatsApp général)" }
              - { label: "Auteur", name: "author", widget: "string", required: false, default: "Admin" }
              - { label: "Lien de postulation", name: "applicationUrl", widget: "string", required: false, hint: "URL directe pour postuler (optionnel)" }
              - { label: "Tags supplémentaires", name: "tags", widget: "list", required: false, default: [], hint: "Tags pour améliorer la recherche" }
              - { label: "Statut de publication", name: "published", widget: "boolean", required: false, default: false, hint: "Cocher pour publier l'offre (admin seulement)" }
              - { label: "Approbation admin", name: "adminApproved", widget: "hidden", required: false, default: false }

  - name: "entreprises"
    label: "Entreprises partenaires"
    files:
      - label: "Entreprises"
        name: "entreprises"
        file: "public/data/entreprises.json"
        permissions:
          create: admin
          update: admin
          delete: admin
        fields:
          - label: "Entreprises partenaires"
            name: "entreprises"
            widget: "list"
            fields:
              - { label: "Nom de l'entreprise", name: "name", widget: "string", required: true }
              - { label: "Logo", name: "logo", widget: "image", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }

  - name: "settings"
    label: "Paramètres du site"
    files:
      - label: "Paramètres généraux"
        name: "settings"
        file: "public/data/settings.json"
        permissions:
          create: admin
          update: admin
          delete: admin
        fields:
          - label: "Logo du site"
            name: "site_logo"
            widget: "image"
            required: false
            hint: "Logo principal du site Smart Insert"
          - label: "Nom du site"
            name: "site_name"
            widget: "string"
            required: false
            default: "Smart Insert"
          - label: "Slogan"
            name: "slogan"
            widget: "string"
            required: false
            default: "Votre carrière commence ici"
          - label: "Contact WhatsApp"
            name: "whatsapp_contact"
            widget: "string"
            required: false
            default: "+22790143507"
          - label: "Email de contact"
            name: "email_contact"
            widget: "string"
            required: false
            default: "abdoulazizeaboubacare@yahoo.fr"