backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "jobs"
    label: "Offres d'emploi"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Entreprise", name: "company", widget: "string" }
      - { label: "Lieu", name: "location", widget: "string" }
      - { label: "Type de contrat", name: "type", widget: "select", options: ["CDI", "CDD", "Stage", "Consultant", "Freelance"] }
      - { label: "Secteur", name: "sector", widget: "select", options: ["Humanitaire", "Agriculture", "Éducation", "Santé", "Services", "Commerce", "Construction", "Technologie"] }
      - { label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Date d'expiration", name: "expirationDate", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Exigences", name: "requirements", widget: "text" }
      - { label: "Expérience requise", name: "experience", widget: "string" }
      - { label: "Niveau d'éducation", name: "education", widget: "string" }
      - { label: "Compétences", name: "skills", widget: "list", default: [] }
      - { label: "Salaire", name: "salary", widget: "string", required: false }
      - { label: "Auteur", name: "author", widget: "string", required: false }